config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :cocktails, only: [:show, :create, :new, :index, :update, :edit] do
    resources :doses, only: [:create, :new ]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :photo
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true 
  
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates_uniqueness_of :cocktail_id, scope: [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
  end
  
  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end
  
  

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end
  
  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)  
    else
      render "cocktails/show"
    end
  end


  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail) 
  end
  
  private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="banner">
  <div class="container">
    <h1>Hardys Hard Stuff</h1>
    <p>Classic cocktails that will delight all</p>
    <%= link_to 'Add a new cocktail', 'cocktails/new', class: "btn reverse-button" %>
  </div>
</div>



<div class="cards-container">
  <% @cocktails.each do |cocktail| %>
  <%= link_to cocktail_path(cocktail) do  %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo.key, height: 300, width: 400, crop: :fill %>')"> <p><%= cocktail.name %> </p></div>
    <% end %>
  <% end %>
</div>

app/views/cocktails/new.html.erb
<div class="banner-show">
  <div class="container">
    <h1>Hardys Hard Stuff</h1>
  </div>
</div>

<div class="container p-3">
  <div class="cocktail-show d-block">
    <h1 class="pt-3 pl-3">Add a new cocktail</h1>

    <%= simple_form_for @cocktail do |f| %>
      <div class="form-inputs">
        <%= f.input :name, label:"Cocktail name" %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, class: "btn reverse-button" %>
      </div>
    <% end %>
  </div>
  <%= link_to "Back to cocktails", cocktails_path, class: "btn main-button mt-3"  %>
</div>

app/views/cocktails/show.html.erb
<div class="banner-show">
  <div class="container">
    <h1>Hardys Hard Stuff</h1>
  </div>
</div>

<div class="container p-3">
  <div class="cocktail-show">
    <div class="picture">
      <% if @cocktail.photo.attached? %>
    
      

      <div class="picture" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @cocktail.photo.key, height: 300, width: 400, crop: :fill %>')">
      </div>

      <% end %>

    </div>
    <div class="cocktail-info">
      <div class="cocktail-details">
        <h1><%= @cocktail.name %></h1>
        <ul>
          <% @cocktail.doses.each do |dose| %>
            <li><%= dose.description + " - " + dose.ingredient.name %> | <%= link_to 'Remove',
              dose_path(dose),
              method: :delete,
              data: { confirm: "Are you sure?"} %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="form-inputs">
        <%= simple_form_for [@cocktail, @dose] do |f| %>
          <%= f.input :description, label:"Quantity" %>
          <%= f.association :ingredient %>
          <%= f.button :submit, class: "btn reverse-button mb-4" %>
        <% end %>
      </div>
    </div>
  </div>
  <%= link_to "Back to cocktails", cocktails_path, class: "btn main-button mt-3"  %>
</div>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @doses] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hardys Hard Stuff - Cocktails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Bad+Script&family=Damion&family=Montserrat:ital@0;1&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
    <%# <div class="footer">
      <div class="footer-links">
        <a href="https://github.com/matthardy17" target="blank"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="https://www.linkedin.com/in/matt-hardy2291/" target="blank"><i class="fab fa-linkedin"></i></a>
      </div>
    </div> %>
  </body>
</html>